Add Jitpack badges to README
patrykandpatrick/opto pull request #9
Opened 2024-03-11 23:15 UTC by yasanglass

This PR adds a few simple Jitpack badges to the README file:

- Build workflow status
- Latest Jitpack version (with status)
- Downloads per month

2024-03-14 11:09 UTC, patrickmichalik requested changes
Hello, and thanks for the PR!

2024-03-14 11:09 UTC, patrickmichalik commented on README.md
> +[![](https://jitpack.io/v/patrykandpatrick/opto/month.svg)](https://jitpack.io/#patrykandpatrick/opto)
I’ve navigated to this URL on a few devices, and the badge either takes a long time to load or doesn’t load at all. Thus, I’d suggest removing it.

```suggestion
```

2024-03-14 11:09 UTC, patrickmichalik commented on README.md
> +[![Build](https://github.com/patrykandpatrick/opto/workflows/Build/badge.svg)](https://github.com/patrykandpatrick/opto/actions/workflows/build.yml)
I’d say “Build” is quite general and might be slightly confusing. How about this?

```suggestion
[![Build status](https://github.com/patrykandpatrick/opto/workflows/Build/badge.svg)](https://github.com/patrykandpatrick/opto/actions/workflows/build.yml)
```

2024-03-14 11:09 UTC, patrickmichalik commented on README.md
> +[![](https://jitpack.io/v/patrykandpatrick/opto.svg)](https://jitpack.io/#patrykandpatrick/opto)
I’d suggest adding alternative text here too.

```suggestion
[![Latest version](https://jitpack.io/v/patrykandpatrick/opto.svg)](https://jitpack.io/#patrykandpatrick/opto)
```

2024-03-14 11:30 UTC, yasanglass commented on README.md
> +[![](https://jitpack.io/v/patrykandpatrick/opto/month.svg)](https://jitpack.io/#patrykandpatrick/opto)
I noticed that but I do not have the same issue on my projects that have it added on the README. I suspect it gets cached if its used more frequently or something like that. Removed it anyway.

2024-03-18 13:23 UTC, patrickmichalik commented on README.md
> +[![](https://jitpack.io/v/patrykandpatrick/opto/month.svg)](https://jitpack.io/#patrykandpatrick/opto)
Ah, got it. We’ll keep that in mind and potentially re-add the badge. Thanks!

2024-03-18 13:24 UTC, patrickmichalik approved these changes
Cheers!

2024-03-18 13:24 UTC, merged